-- AlterTable
ALTER TABLE "Patient" ADD COLUMN     "cardNo" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "facility" TEXT,
ADD COLUMN     "houseNo" TEXT,
ADD COLUMN     "idNumber" TEXT,
ADD COLUMN     "kebele" TEXT,
ADD COLUMN     "maritalStatus" TEXT,
ADD COLUMN     "subCity" TEXT,
ADD COLUMN     "woreda" TEXT;

-- CreateTable
CREATE TABLE "ANCRecord" (
    "id" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "lmp" TIMESTAMP(3),
    "edd" TIMESTAMP(3),
    "gravida" INTEGER,
    "para" INTEGER,
    "abortion" INTEGER,
    "ectopicPreg" INTEGER,
    "childrenAlive" INTEGER,
    "diabetesMellitus" BOOLEAN,
    "cardiacDisease" BOOLEAN,
    "chronicHypertension" BOOLEAN,
    "otherMedicalCondition" BOOLEAN,
    "otherMedicalConditionText" TEXT,
    "vdrl" TEXT,
    "hiv" TEXT,
    "hbsAg" TEXT,
    "rbs" TEXT,
    "fbs" TEXT,
    "bloodGroupRh" TEXT,
    "ua" TEXT,
    "td" TEXT,
    "generalExamGeneral" TEXT,
    "generalExamPallor" TEXT,
    "jaundice" BOOLEAN,
    "chestAbnormality" BOOLEAN,
    "heartAbnormality" BOOLEAN,
    "vulvarUlcer" BOOLEAN,
    "vaginalDischarge" BOOLEAN,
    "pelvicMass" BOOLEAN,
    "cervicalLesion" BOOLEAN,
    "uterineSizeWks" INTEGER,
    "dangerSignsAdvised" BOOLEAN,
    "birthPreparednessAdvised" BOOLEAN,
    "motherHivTestAccepted" BOOLEAN,
    "hivTestResult" TEXT,
    "hivTestResultReceived" BOOLEAN,
    "counseledInfantFeeding" BOOLEAN,
    "referredForCare" BOOLEAN,
    "partnerHivTestResult" TEXT,
    "gaLmp" TEXT,
    "complaints" TEXT,
    "bloodPressure" TEXT,
    "weightKg" DOUBLE PRECISION,
    "pallor" TEXT,
    "hemoglobin" TEXT,
    "uterineHeightWks" INTEGER,
    "presentation" TEXT,
    "descent" TEXT,
    "fetalHeartRate" TEXT,
    "remarks" TEXT,
    "nextFollowUpDate" TIMESTAMP(3),
    "dangerSignsIdentified" TEXT,
    "actionAdviceCounselling" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ANCRecord_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ANCRecord" ADD CONSTRAINT "ANCRecord_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
