import { Router } from "express";
import usersRouter from "./users.router";
import clinicsRouter from "./clinics.router";
import patientsRouter from "./patients.router";
import visitsRouter from "./visits.router";
import ultrasoundsRouter from "./ultrasounds.router";
import gbvReportsRouter from "./gbv-reports.router";
import teleconsultsRouter from "./teleconsults.router";
import alertsRouter from "./alerts.router";
import appointmentsRouter from "./appointments.router";
import syncRouter from "./sync.router";
import activityRouter from "./activity.router";
import settingsRouter from "./settings.router";
import filesRouter from "./files.router";
import riskRouter from "./risk.router";
import mongoRouter from "./mongo.router";
const v1Router = Router();

v1Router.use("/users", usersRouter);
v1Router.use("/clinics", clinicsRouter);
v1Router.use("/patients", patientsRouter);
v1Router.use("/visits", visitsRouter);
v1Router.use("/ultrasounds", ultrasoundsRouter);
v1Router.use("/gbv-reports", gbvReportsRouter);
v1Router.use("/teleconsults", teleconsultsRouter);
v1Router.use("/alerts", alertsRouter);
v1Router.use("/appointments", appointmentsRouter);
v1Router.use("/sync", syncRouter);
v1Router.use("/activity", activityRouter);
v1Router.use("/settings", settingsRouter);
v1Router.use("/files", filesRouter);
v1Router.use("/risk", riskRouter);
v1Router.use("/mongo", mongoRouter);
export default v1Router;
