import { Model, Schema, model } from "mongoose";

const syncStatusField = { type: String, enum: ["synced", "pending", "conflict"] };

const patientSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    fullName: { type: String, required: true },
    unfpId: { type: String, required: true },
    cardNo: String,
    phone: String,
    email: String,
    age: Number,
    address: String,
    subCity: String,
    woreda: String,
    kebele: String,
    houseNo: String,
    facility: String,
    maritalStatus: String,
    idNumber: String,
    emergencyContact: String,
    emergencyPhone: String,
    createdAt: Date,
    createdById: String,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const visitSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    pregnancyId: String,
    recordedById: String,
    visitDate: Date,
    visitNumber: Number,
    visitType: String,
    gestationalAge: Number,
    bloodPressure: String,
    temperature: Number,
    weight: Number,
    symptoms: String,
    notes: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
    visitCaseCategory: String,
    ancRecordId: String,
    pncVisitId: String,
    gbvReportId: String,
    gbvScreeningId: String,
  },
  { versionKey: false, strict: true },
);

const ultrasoundSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    visitId: String,
    imageUrl: String,
    description: String,
    gestationalAge: Number,
    capturedAt: Date,
    gain: Number,
    depth: Number,
    dynamicRange: Number,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
    annotations: String,
    takenById: String,
  },
  { versionKey: false, strict: true },
);

const gbvReportSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    incidentType: String,
    incidentDate: Date,
    allegedPerpetratorEncrypted: String,
    victimStatementEncrypted: String,
    referralActionEncrypted: String,
    referral: Boolean,
    referralInfo: String,
    attachmentUrl: String,
    highRisk: Boolean,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
    recordedById: String,
  },
  { versionKey: false, strict: true },
);

const gbvScreeningSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    recordedById: String,
    survivorConsentSignature: String,
    caseWorkerConsentSignature: String,
    gbvHistory: String,
    temperature: String,
    weightKg: Number,
    heightCm: Number,
    bmiIndex: Number,
    bloodPressure: String,
    pulse: String,
    respiratoryRate: String,
    oxygenSaturation: String,
    physicalExamination: String,
    workingDiagnosis: String,
    laboratoryResults: String,
    pregnancyTestingResults: String,
    hivTestingResults: String,
    stiTestingResults: String,
    postExposureProphylaxisTreatment: String,
    emergencyContraceptiveProvision: String,
    typeOfUltrasound: String,
    ultrasoundMore: String,
    smartUltrasoundRecommendation: String,
    treatmentPlan: String,
    treatmentRx: String,
    continuationSheet: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
    gbvReportId: String,
  },
  { versionKey: false, strict: true },
);

const srhRegistrationSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    recordedById: String,
    clientConsentSignature: String,
    healthProfessionalConsentSignature: String,
    srhServiceType: String,
    history: String,
    temperature: String,
    weightKg: Number,
    heightCm: Number,
    bmiIndex: Number,
    bloodPressure: String,
    pulse: String,
    respiratoryRate: String,
    oxygenSaturation: String,
    physicalExamination: String,
    workingDiagnosis: String,
    laboratoryResults: String,
    typeOfUltrasound: String,
    ultrasoundMore: String,
    smartUltrasoundRecommendation: String,
    treatmentPlan: String,
    treatmentRx: String,
    continuationSheet: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const ancRecordSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    clientConsentSignature: String,
    healthProfessionalConsentSignature: String,
    lmp: Date,
    edd: Date,
    gravida: Number,
    para: Number,
    abortion: Number,
    ectopicPreg: Number,
    childrenAlive: Number,
    pastObstetricHistory: Schema.Types.Mixed,
    diabetesMellitus: Boolean,
    diabetesMellitusMoreInfo: String,
    cardiacDisease: Boolean,
    cardiacDiseaseMoreInfo: String,
    chronicHypertension: Boolean,
    chronicHypertensionMoreInfo: String,
    otherMedicalCondition: Boolean,
    otherMedicalConditionText: String,
    vdrl: String,
    hiv: String,
    hbsAg: String,
    rbs: String,
    fbs: String,
    bloodGroupRh: String,
    ua: String,
    td: String,
    generalExamGeneral: String,
    generalExamPallor: String,
    jaundice: Boolean,
    chestAbnormality: Boolean,
    chestAbnormalityMoreInfo: String,
    heartAbnormality: Boolean,
    heartAbnormalityMoreInfo: String,
    vulvarUlcer: Boolean,
    vaginalDischarge: Boolean,
    pelvicMass: Boolean,
    cervicalLesion: Boolean,
    uterineSizeWks: Number,
    dangerSignsAdvised: Boolean,
    birthPreparednessAdvised: Boolean,
    motherHivTestAccepted: Boolean,
    hivTestResult: String,
    hivTestResultReceived: Boolean,
    counseledInfantFeeding: Boolean,
    referredForCare: Boolean,
    partnerHivTestResult: String,
    gaLmp: String,
    complaints: String,
    bloodPressure: String,
    weightKg: Number,
    pallor: String,
    hemoglobin: String,
    uterineHeightWks: Number,
    presentation: String,
    descent: String,
    fetalHeartRate: String,
    remarks: String,
    nextFollowUpDate: Date,
    dangerSignsIdentified: String,
    actionAdviceCounselling: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const deliverySchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    pregnancyId: String,
    recordedById: String,
    clientConsentSignature: String,
    healthProfessionalConsentSignature: String,
    deliveryDate: Date,
    deliveryTime: String,
    referral: Boolean,
    referralInfo: String,
    amtsl: String,
    placenta: String,
    laceration: String,
    obstetricCxManaged: Boolean,
    aphManaged: Boolean,
    rupturedUx: Boolean,
    eclampsiaManaged: Boolean,
    pphManaged: Boolean,
    promSepsisManaged: Boolean,
    obstPrologLaborManaged: Boolean,
    deliveryAssistanceMeasures: String,
    deliveryAssistanceMore: String,
    hivCounsTestingOffered: String,
    hivTestingAccepted: String,
    hivTestResult: String,
    arvpxForMothers: String,
    arvpxForNb: String,
    feedingOptionEbf: String,
    rf: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const pncVisitSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    deliveryId: String,
    recordedById: String,
    clientConsentSignature: String,
    healthProfessionalConsentSignature: String,
    visitDate: Date,
    bloodPressure: String,
    tpr: String,
    temperature: Number,
    uterusContracted: String,
    dribblingLeakingUrine: String,
    anemia: String,
    vaginalDischarge: String,
    breast: String,
    vitaminA: String,
    counselingDangerSigns: String,
    babyBreathing: String,
    babyBreastFeeding: String,
    babyWeightGm: Number,
    immunization: String,
    hivTested: String,
    hivTestResult: String,
    arvPxForMother: String,
    arvPxForNewborn: String,
    feedingOption: String,
    motherReferredToCare: String,
    newbornReferredToCare: String,
    fpCounseledAndProvided: String,
    remark: String,
    actionTaken: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const pregnancySchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    startDate: Date,
    estimatedDue: Date,
    active: Boolean,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const referralSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    patientId: String,
    createdById: String,
    referredTo: String,
    reason: String,
    notesEncrypted: String,
    attachmentUrl: String,
    status: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const messageSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    conversationId: String,
    senderId: String,
    recipientId: String,
    body: String,
    attachmentUrl: String,
    readAt: Date,
    createdAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const conversationSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    user1Id: String,
    user2Id: String,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const userSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    passwordHash: String,
    phone: String,
    email: String,
    fullName: String,
    displayId: String,
    profileImageUrl: String,
    preferredLanguage: String,
    clinicId: String,
    isActive: Boolean,
    mustChangePassword: Boolean,
    createdAt: Date,
    updatedAt: Date,
    syncStatus: syncStatusField,
    syncedAt: Date,
    syncError: String,
  },
  { versionKey: false, strict: true },
);

const roleSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    name: { type: String, unique: true },
    description: String,
    createdAt: Date,
  },
  { versionKey: false, strict: true },
);

const userRoleSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    userId: String,
    roleId: String,
    grantedBy: String,
    createdAt: Date,
  },
  { versionKey: false, strict: true },
);

export const entityModels = {
  Patient: model("MongoPatient", patientSchema),
  Visit: model("MongoVisit", visitSchema),
  Ultrasound: model("MongoUltrasound", ultrasoundSchema),
  GBVReport: model("MongoGBVReport", gbvReportSchema),
  GBVScreening: model("MongoGBVScreening", gbvScreeningSchema),
  SRHRegistration: model("MongoSRHRegistration", srhRegistrationSchema),
  ANCRecord: model("MongoANCRecord", ancRecordSchema),
  Delivery: model("MongoDelivery", deliverySchema),
  PNCVisit: model("MongoPNCVisit", pncVisitSchema),
  Pregnancy: model("MongoPregnancy", pregnancySchema),
  Referral: model("MongoReferral", referralSchema),
  Message: model("MongoMessage", messageSchema),
  Conversation: model("MongoConversation", conversationSchema),
  User: model("MongoUser", userSchema),
  Role: model("MongoRole", roleSchema),
  UserRole: model("MongoUserRole", userRoleSchema),
} as const;

export type PrismaSyncEntity = keyof typeof entityModels;

export function listPrismaSyncEntities() {
  return Object.keys(entityModels) as PrismaSyncEntity[];
}

export function getMongoModelForEntity(entityType: PrismaSyncEntity): Model<any> {
  const found = entityModels[entityType];
  if (!found) throw new Error(`No Mongo model for entity ${entityType}`);
  return found as Model<any>;
}
